### ISSUE TITLE
Google calendar subscription URL invalid (?)

### ISSUE THREAD

**Issue by isabelizimm** [JesperDramsch/python-deadlines#32]
Hello there! First off, thank you for maintaining this excellent community resource. It's so nice to be able to see all these conferences in one place 🫶 When clicking on the link to add events to my calendar OR the link to subscribe to this calendar, I am getting an error. This is what I am seeing pop up ⏬ 

<img width="337" alt="Screenshot 2024-11-12 at 11 39 44 AM" src="https://github.com/user-attachments/assets/022ef177-52ca-4b2b-909b-be8f86a48a95">

I also tried to add the calendar manually with the url https://calendar.google.com/calendar/r?cid=https://pythondeadlin.es/python-conferences.ics with the same result. Let me know if you need any other info!

**Comment by JesperDramsch** [comment]
Hi @isabelizimm thank you for reporting this!

That's very odd, it used to work and now does the same for me. I'll do my best to debug this, but it might be a few weeks as I'm about to board a plane. 

In the meantime, you will be able to add it manually by adding 
https://pythondeadlin.es/python-conferences.ics
on this page:
https://calendar.google.com/calendar/u/0/r/settings/addbyurl?pli=1

Sorry for the inconvenience!

**Comment by isabelizimm** [comment]
Thanks for the update! No rush, just wanted to let you know. Safe travels! 🛩️

**Comment by JesperDramsch** [comment]
Thank youu! 
I thank the answer is that Ical is difficult and I somehow messed it up. I'll try and fix it as soon as I can. Thanks for flagging this! 
-------- Original Message --------On 12/11/2024 23:02, Isabel Zimmerman  wrote:
Thanks for the update! No rush, just wanted to let you know. Safe travels! 🛩️

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/JesperDramsch/python-deadlines/issues/32#issuecomment-2471673000",
"url": "https://github.com/JesperDramsch/python-deadlines/issues/32#issuecomment-2471673000",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JesperDramsch** [comment]
Hi @isabelizimm I think I finally managed to fix it. Even with correct timezones. Thanks for the ping!

**Comment by JesperDramsch** [comment]
@all-contributors add @isabelizimm for bug
